name: uicons_pro
description: "Un paquete de iconos para Flutter basado en UIcons"
version: 1.0.0
homepage: https://github.com/maicolodont/uicons_pro/

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: RegularRounded
      fonts:
        - asset: lib/fonts/uicons-regular-rounded.ttf
    - family: BoldRounded
      fonts:
        - asset: lib/fonts/uicons-bold-rounded.ttf
    - family: SolidRounded
      fonts:
        - asset: lib/fonts/uicons-solid-rounded.ttf
    - family: ThinRounded
      fonts:
        - asset: lib/fonts/uicons-thin-rounded.ttf
